force_estimator:
  rate: 100.0
  use_momentum_based: false
  is_model_floating_base: false
  model_type: RBDL
  links: [dagana_1_tcp]
  chains: [arm]
  dagana_1_tcp:
    dofs: [0, 1, 2, 3, 4, 5]
  ignored_joints: [dagana_1_tcp]
  svd_threshold: 0.05
  #reset offset
  sec_to_reset: 3
  #log
  enable_log: false
  #ref frame wrt forces are published
  ref_frame: base_link
  #filter
  enable_filter: false
  filter_damp: 0.8
  filter_bw: 3
  filter_dead_zone: 0
  #markers
  pub_arrows: false
  