force_estimator:
  rate: 100.0
  use_momentum_based: false
  is_model_floating_base: true
  model_type: RBDL
  links: [arm1_8, arm2_8]
  chains: [left_arm, right_arm]
  arm1_8:
    dofs: [0, 1, 2]
  arm2_8:
    dofs: [0, 1, 2]